### PR TITLE
Ensure no duplicate product rewrites ever exists

### PR DESCRIPTION
**Pull request by misthero**
This little check during product save/add/update will ensure we will never have 2 identical urls for different products in the same language.

The approach is similar to wat you can see in Drupal CMS, where if you have 2 nodes, or categories with the same url, it will automatically append a number at the end.

The idea is that if the user doesn't notice there are 2 products with the same name the ecommerce will keep working, this can happen when you sell something like dresses or other general products, it can happen to have many "t-shirt" products.

If the user doesn't like the rewrite he chan always change it (ensuring it is unique)

### CODE REVIEW

**Comment by misthero** [comment]
> What happens if I a "foo" product, then add again "foo" (generating "foo-2"), later I forgot and go to create "foo" again .. but "foo-2" already exists too

it will be foo-3 and so on, it will check every combination, there is a while and a counter doing that, it will check per language, since every language should already have his unique url prefixed /en/.. or something

of course if you have 10 languages enabled and 10.000 products with the exact same name the save process can slow down... but hey, something is wrong there.

at the moment if you have two or 1.000 products with the same name, only the first one you created will works, because every product have the same exact url.. so this module is unable to decide what to do.

the idea behind this is that if you forget to choose a better clean url for your "same name product" you get a number on the end of that product url instead of a non-working one. Than you will probably notice it and go change the url to something nicer.

If you don't, the system will still work, it wont be good for SEO, having hundreds of foo-1, foo-2, foo-3 .. but that is your choosing, you can always go back and edit those urls.

if you are ok with this I will do what you asks.

**Comment by drAlberT** [comment]
Uhmm .. it looks quite good, it should work.

To be honest I'd prefer another approach:

1. catch the duplicate creation request
2. alert the user, explaining what is happening
3. refuse to create the non-unique slug

What do you think about this approach? it is a O(0) approach, it has no magic, it makes the user responsible for his actions, making the module logic cleaner and simpler (thus less bug-prone)

**Comment by misthero** [comment]
I'm ok with alerting the user about what is happening, I'm unsure about preventing the product save until a correct non-unique slug is entered. You are forcing the user to do something the base prestashop doesn't. 

what about the user is not using the backoffice but importing products from csv or something? We are adding a problem instead of solving it if we prevent the saving.

If you think about it, actually you can use  "foo" as product slug multiple times, on base prestashop you have the product id added to create the unique slug. '1234-foo', '432-foo', etc.. almost the same with this solution.

Maybe it should save the product anyway and show a message like: 
"Another product exists with the same slug "foo", to avoid conflicts it has been changed to "foo-0". Please correct this in SEO tab".

or something like that..

**Comment by drAlberT** [comment]
Uhmm .. ok you convinced me :) It's ok to alert the user and then *propose* the "numbered" slug .. it would be great to just propose, before saving; giving the user the possibility to better handle this stuff or the *rensposibility* of going on .. 

I prefer not to save and then alert because I had a number of issues with "temporary" stuff with Google bot .. it resemble to the "traffic auxiliary ppl", if you make an error it is there indexig it **soon** :)

Just for the sake of knowled: 
regarding to deny save I don't get your point about bulk imports .. we'd not interfer with them .. ok they'd bypass the check but nothing more ..

**Pull request closed without merging**
